### ISSUE TITLE
How to add inline javascript

### ISSUE THREAD

**Issue by ncri** [doomspork/phoenix_slim_example#4]
I tried like i do it with ruby on rails:

```
javascript:
  my js;
  ....
```

Doesn't work, creates `<javascript>` html tags instead.

What does work is:

```
<script>
  = {:safe, "my js;"}
</script>
```

But that is not very convenient.

**Comment by doomspork** [comment]
Hi @ncri, we don't currently support other embedded engine but there is a PR to add support: https://github.com/slime-lang/slime/pull/101

Once this is merged and release you should be able to inline Javascript 👍

**Comment by ncri** [comment]
Great, thanks, hope it can be merged soon! :)
